apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopstream-frontend
  namespace: shopstream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopstream-frontend
  template:
    metadata:
      labels:
        app: shopstream-frontend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        image: akashrajeshnair/shopstream-frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: shopstream-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 