apiVersion: v1
kind: Service
metadata:
  name: shopstream-frontend
  namespace: shopstream
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  selector:
    app: shopstream-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: shopstream-backend
  namespace: shopstream
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: shopstream-backend
---
apiVersion: v1
kind: Service
metadata:
  name: shopstream-postgres
  namespace: shopstream
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: shopstream-postgres 